### ISSUE TITLE
Possible mistake in chapter 3 part B exercise 3 ( and others)

### ISSUE THREAD

**Issue by ameligrana** [narodnik/abstract-algebra-pinter-solutions#1]
Hi! Thank you for the work ! I noticed a possible mistake in exercise 3, you say that the operation doesn't form a group because x_1 e_1 = x_1 is not uniquely determined , but it is not true because it happens just when x_1 = 0 not always so the only element that is an identity is 1. The operation is , indeed, not a group but because it has not an inverse in all cases. This possible flaw is also in some other exercise

**Comment by narodnik** [comment]
Amazing, can you make a pull request with corrections? Happy to pull them

**Comment by ameligrana** [comment]
yes, sure but I have some problem in undestanding which the right way to correct your html files, should I use pandoc in someway? or should I correct them in the raw file (I'm a not so used to html)?

**Comment by narodnik** [comment]
I didn't write the html files. They were pulled from here:

http://web.archive.org/web/20180603092112/http://www.math.wisc.edu/~mstemper2/Math/Pinter/

I just made a mirror of them. I was using his website up until it stopped so I decided to finish his work here.

**Comment by ameligrana** [comment]
ok, perfect , I'll try to fix the flaws !
