### ISSUE TITLE
Part F of chapter 3 is missing 

### ISSUE THREAD

**Issue by ameligrana** [narodnik/abstract-algebra-pinter-solutions#4]
Part F of chapter 3 is missing, maybe we can fix it by writing an html file with the solution, I have some problem with exercise 6 though because it is not given the definition of subtraction ( maybe the value c so that b+c = a ? what do you think?).

**Comment by narodnik** [comment]
These early chapters I kinda rushed through without doing all the exercises. Things started getting harder around chapter 7-8 so I begun slowing down and doing every exercise. The answers, I just copied from mstemper
