### ISSUE TITLE
Chapter 2 Section A Problem 2

### ISSUE THREAD

**Issue by yagnisazzou** [narodnik/abstract-algebra-pinter-solutions#5]
Your answer indicates that a*b is an operation. However, the ordered pair (2,1) would take the solution out of the set because ln(1) = 0. Also, any value between 0 and 1 for b would produce a negative number, also taking the solution out of the set. Therefore, a * b in this question is not an operation.

**Comment by narodnik** [comment]
Feel free to submit an answer. I'll pull.
