### ISSUE TITLE
Chapter 8 Section A Exercise 4(f)

### ISSUE THREAD

**Issue by ChosenOne2241** [narodnik/abstract-algebra-pinter-solutions#6]
Unlike what ``Chapter08A.html`` says, its answer from the textbook is perfectly correct:
γ^3 α^(-1) = (1 2 3 4 5) (4 1 7 3) = (1 7 4 2 3 5).
Hopefully you can fix it before long, Amir.

P.S.: I personally appreciate your effort of maintaining this project. Do you consider rewriting the solutions of the first 15 chapters (maybe with MathJax for better mathematical display), since they are a bundle of the original webpages fetched from Michael F. Stemper's personal site? No pressure, I am just curious.

**Comment by narodnik** [comment]
Yeah I didn't write those solutions, just copied them over. It's a lot of work tho to rewrite them so not planning to do that.

Happy to pull any fixes or rewrites if you submit.
